import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { AgeVerificationDialog } from "@/components/age-verification-dialog";
import { Toaster } from "react-hot-toast";
import { ProductProvider } from "@/lib/provider/product-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProductProvider>
          <Suspense fallback={null}>
            <AgeVerificationDialog />
            <Toaster />
          </Suspense>
          {children}
        </ProductProvider>
      </body>
    </html>
  );
}
