import type { Metadata } from "next";
import { CartProvider } from "@/lib/provider/cart-context";
import { Header } from "@/components/header";
import { Navigation } from "@/components/navigation";
import { Footer } from "@/components/footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <CartProvider>
        <Header />
        <Navigation />
        {children}

        <Footer />
      </CartProvider>
    </main>
  );
}
